/* Generated by Yosys 0.64 (git sha1 d8dab5b32666564eca8e18f412973853ce006e61, clang++ 21.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:70" *)
(* generator = "Amaranth" *)
module my1541_top(i_ram_data, i_track_data, i_track_len, i_clk_1mhz_ph1_en, i_clk_1mhz_ph2_en, i_iec_atn_in, i_iec_data_in, i_iec_clock_in, clk, rst, o_addr, o_ram_data, o_ram_we, o_track_addr, o_track_no, o_led_on, o_motor_on, o_iec_data_out, o_iec_clock_out, o_debug_6502_valid, o_debug_6502_sync
, o_debug_6502_addr, o_debug_6502_data, o_debug_6502_regs, i_rom_data);
  reg \$auto$verilog_backend.cc:2445:dump_module$1  = 0;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:34" *)
  input [7:0] i_ram_data;
  wire [7:0] i_ram_data;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:39" *)
  input [31:0] i_track_data;
  wire [31:0] i_track_data;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:40" *)
  input [12:0] i_track_len;
  wire [12:0] i_track_len;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:27" *)
  input i_clk_1mhz_ph1_en;
  wire i_clk_1mhz_ph1_en;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:30" *)
  input i_clk_1mhz_ph2_en;
  wire i_clk_1mhz_ph2_en;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:49" *)
  input i_iec_atn_in;
  wire i_iec_atn_in;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:50" *)
  input i_iec_data_in;
  wire i_iec_data_in;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:52" *)
  input i_iec_clock_in;
  wire i_iec_clock_in;
  (* src = "/private/tmp/myc64-amaranth-venv/lib/python3.14/site-packages/amaranth/hdl/_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "/private/tmp/myc64-amaranth-venv/lib/python3.14/site-packages/amaranth/hdl/_ir.py:283" *)
  input rst;
  wire rst;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:29" *)
  output [15:0] o_addr;
  wire [15:0] o_addr;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:34" *)
  output [7:0] o_ram_data;
  wire [7:0] o_ram_data;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:36" *)
  output o_ram_we;
  wire o_ram_we;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:38" *)
  output [10:0] o_track_addr;
  wire [10:0] o_track_addr;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:221" *)
  output [6:0] o_track_no;
  reg [6:0] o_track_no = 7'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:189" *)
  output o_led_on;
  wire o_led_on;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:188" *)
  output o_motor_on;
  wire o_motor_on;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:51" *)
  output o_iec_data_out;
  wire o_iec_data_out;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:53" *)
  output o_iec_clock_out;
  wire o_iec_clock_out;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:27" *)
  output o_debug_6502_valid;
  wire o_debug_6502_valid;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:38" *)
  output o_debug_6502_sync;
  wire o_debug_6502_sync;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:29" *)
  output [15:0] o_debug_6502_addr;
  wire [15:0] o_debug_6502_addr;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:40" *)
  output [7:0] o_debug_6502_data;
  wire [7:0] o_debug_6502_data;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:41" *)
  output [63:0] o_debug_6502_regs;
  wire [63:0] o_debug_6502_regs;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:32" *)
  input [7:0] i_rom_data;
  wire [7:0] i_rom_data;
  wire \$1 ;
  wire \$10 ;
  wire \$11 ;
  wire \$12 ;
  wire \$13 ;
  wire \$14 ;
  wire \$15 ;
  wire \$16 ;
  wire \$17 ;
  wire \$18 ;
  wire \$19 ;
  wire \$2 ;
  wire \$20 ;
  wire [2:0] \$21 ;
  wire [16:0] \$22 ;
  wire \$23 ;
  wire \$24 ;
  wire [7:0] \$25 ;
  wire [3:0] \$26 ;
  wire \$27 ;
  wire [2:0] \$28 ;
  wire \$29 ;
  wire \$3 ;
  wire \$30 ;
  wire \$31 ;
  wire [2:0] \$32 ;
  wire \$33 ;
  wire \$34 ;
  wire [7:0] \$35 ;
  wire [7:0] \$36 ;
  reg [1:0] \$37 ;
  reg [15:0] \$38 ;
  reg [2:0] \$39 ;
  wire \$4 ;
  reg [7:0] \$40 ;
  reg [2:0] \$41 ;
  reg [9:0] \$42 ;
  reg [1:0] \$43 ;
  reg [6:0] \$44 ;
  wire \$5 ;
  wire \$6 ;
  wire \$7 ;
  wire [5:0] \$78 ;
  wire \$8 ;
  wire \$9 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:193" *)
  wire atna;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:176" *)
  reg [2:0] bit_cntr = 3'h0;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:171" *)
  wire block_sync;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:173" *)
  wire [7:0] \byte ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:172" *)
  wire byte_sync;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:27" *)
  wire clk_1mhz_ph1_en;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:28" *)
  wire clk_1mhz_ph2_en;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:30" *)
  wire clk_1mhz_ph_en;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:30" *)
  wire \clk_1mhz_ph_en$54 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:87" *)
  wire [15:0] cpu_addr;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:89" *)
  reg [7:0] cpu_di;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:90" *)
  wire [7:0] cpu_do;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:88" *)
  wire cpu_we;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:191" *)
  wire [1:0] data_density;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:144" *)
  wire decoder_enable;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:145" *)
  reg [1:0] decoder_enable_cntr = 2'h0;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:186" *)
  wire [1:0] head_step_dir;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:187" *)
  reg [1:0] head_step_dir_p = 2'h0;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:32" *)
  wire [3:0] i_addr;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:32" *)
  wire [3:0] \i_addr$56 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:42" *)
  wire i_ca1;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:42" *)
  wire \i_ca1$72 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:31" *)
  wire i_cs;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:31" *)
  wire \i_cs$55 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:30" *)
  wire [7:0] i_data;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:34" *)
  wire [7:0] \i_data$53 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:34" *)
  wire [7:0] \i_data$58 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:33" *)
  wire i_irq;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:37" *)
  wire [7:0] i_pa;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:39" *)
  wire [7:0] i_pb;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:39" *)
  wire [7:0] \i_pb$78 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:35" *)
  wire i_so;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:33" *)
  wire i_we;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:33" *)
  wire \i_we$57 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:189" *)
  wire led_ctrl;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:188" *)
  wire motor_ctrl;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:29" *)
  wire [15:0] \o_addr$42 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:35" *)
  wire [7:0] o_data;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:35" *)
  wire [7:0] \o_data$30 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:31" *)
  wire [7:0] \o_data$46 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:39" *)
  wire [15:0] o_debug_addr;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:40" *)
  wire [7:0] o_debug_data;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:41" *)
  wire [63:0] o_debug_regs;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:38" *)
  wire o_debug_sync;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:37" *)
  wire o_debug_valid;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:51" *)
  wire o_irq;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:51" *)
  wire \o_irq$41 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:40" *)
  wire [7:0] o_pb;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:40" *)
  wire [7:0] \o_pb$75 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:32" *)
  wire o_we;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:82" *)
  reg ram_cs;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:175" *)
  reg [9:0] read_bits = 10'h000;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:83" *)
  reg rom_cs;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:152" *)
  reg [15:0] track_bit_cntr = 16'h0000;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:153" *)
  reg [2:0] track_bit_cntr_p = 3'h0;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:154" *)
  reg [7:0] track_byte_shift = 8'h00;
  (* init = 7'h00 *)
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:221" *)
  wire [6:0] track_no;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:84" *)
  reg via1_cs;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:85" *)
  reg via2_cs;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:190" *)
  wire write_protect;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:145" *)
  always @(posedge clk)
    decoder_enable_cntr <= \$37 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:152" *)
  always @(posedge clk)
    track_bit_cntr <= \$38 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:153" *)
  always @(posedge clk)
    track_bit_cntr_p <= \$39 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:154" *)
  always @(posedge clk)
    track_byte_shift <= \$40 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:176" *)
  always @(posedge clk)
    bit_cntr <= \$41 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:175" *)
  always @(posedge clk)
    read_bits <= \$42 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:187" *)
  always @(posedge clk)
    head_step_dir_p <= \$43 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:221" *)
  always @(posedge clk)
    o_track_no <= \$44 ;
  assign \$1  = o_addr <= (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:93" *) 11'h7ff;
  assign \$2  = o_addr >= (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:96" *) 13'h1800;
  assign \$3  = o_addr <= (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:96" *) 13'h180f;
  assign \$4  = \$2  & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:96" *) \$3 ;
  assign \$5  = o_addr >= (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:99" *) 13'h1c00;
  assign \$6  = o_addr <= (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:99" *) 13'h1c0f;
  assign \$7  = \$5  & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:99" *) \$6 ;
  assign \$8  = o_addr >= (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:102" *) 16'hc000;
  assign \$9  = o_addr <= (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:102" *) 16'hffff;
  assign \$10  = \$8  & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:102" *) \$9 ;
  assign i_irq = o_irq | (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:120" *) \o_irq$41 ;
  assign o_ram_we = cpu_we & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:141" *) ram_cs;
  assign \$11  = ! (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:146" *) decoder_enable_cntr;
  assign decoder_enable = i_clk_1mhz_ph2_en & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:146" *) \$11 ;
  assign \$12  = bit_cntr == (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:178" *) 3'h7;
  assign byte_sync = decoder_enable & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:178" *) \$12 ;
  assign block_sync = & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:179" *) read_bits;
  assign \$13  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:197" *) i_iec_data_in;
  assign \$14  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:198" *) o_pb[1];
  assign \$15  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:198" *) i_iec_atn_in;
  assign \$16  = o_pb[4] ^ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:198" *) \$15 ;
  assign \$17  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:198" *) \$16 ;
  assign o_iec_data_out = \$14  & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:198" *) \$17 ;
  assign \$18  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:199" *) i_iec_clock_in;
  assign o_iec_clock_out = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:200" *) o_pb[3];
  assign \$19  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:202" *) i_iec_atn_in;
  assign i_ca1 = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:203" *) i_iec_atn_in;
  assign \i_ca1$72  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:206" *) byte_sync;
  assign \$20  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:213" *) block_sync;
  assign \$21  = decoder_enable_cntr + (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:148" *) 1'h1;
  assign \$22  = track_bit_cntr + (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:158" *) 1'h1;
  assign \$23  = track_bit_cntr[15:3] == (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:160" *) i_track_len;
  assign \$24  = ! (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:163" *) track_bit_cntr_p;
  assign \$78  = track_bit_cntr[4:3] * (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:164" *) 4'h8;
  assign \$25  = i_track_data >> \$78 ;
  assign \$26  = bit_cntr + (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:181" *) 1'h1;
  assign \$27  = o_track_no < (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:224" *) 7'h54;
  assign \$28  = head_step_dir_p + (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:224" *) 1'h1;
  assign \$29  = \o_pb$75 [1:0] == (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:224" *) \$28 [1:0];
  assign \$30  = \$27  & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:224" *) \$29 ;
  assign \$31  = o_track_no > (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:226" *) 1'h0;
  assign \$32  = head_step_dir_p - (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:226" *) 1'h1;
  assign \$33  = \o_pb$75 [1:0] == (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:226" *) \$32 [1:0];
  assign \$34  = \$31  & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:226" *) \$33 ;
  assign \$35  = o_track_no + (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:225" *) 1'h1;
  assign \$36  = o_track_no - (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:227" *) 1'h1;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:73" *)
  \my1541_top.u_cpu_  u_cpu_ (
    .clk(clk),
    .clk_1mhz_ph2_en(i_clk_1mhz_ph2_en),
    .data_ir(o_debug_6502_data),
    .i_data(cpu_di),
    .i_irq(i_irq),
    .i_so(byte_sync),
    .o_addr(o_addr),
    .o_data(o_ram_data),
    .o_debug_sync(o_debug_6502_sync),
    .o_debug_valid(i_clk_1mhz_ph1_en),
    .o_we(cpu_we),
    .rst(rst)
  );
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:76" *)
  \my1541_top.u_via1  u_via1 (
    .clk(clk),
    .clk_1mhz_ph_en(i_clk_1mhz_ph2_en),
    .i_addr(o_addr[3:0]),
    .i_ca1(i_ca1),
    .i_cs(via1_cs),
    .i_data(o_ram_data),
    .i_pb(i_pb),
    .i_we(cpu_we),
    .o_data(o_data),
    .o_irq(o_irq),
    .reg_orb(o_pb),
    .rst(rst)
  );
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/my1541.py:79" *)
  \my1541_top.u_via2  u_via2 (
    .clk(clk),
    .clk_1mhz_ph_en(i_clk_1mhz_ph2_en),
    .i_addr(o_addr[3:0]),
    .i_ca1(\i_ca1$72 ),
    .i_cs(via2_cs),
    .i_data(o_ram_data),
    .i_pa(read_bits[7:0]),
    .i_pb(\i_pb$78 ),
    .i_we(cpu_we),
    .o_data(\o_data$30 ),
    .o_irq(\o_irq$41 ),
    .reg_orb(\o_pb$75 ),
    .rst(rst)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$1 ) begin end
    \$38  = track_bit_cntr;
    if (decoder_enable) begin
      \$38  = \$22 [15:0];
      if (\$23 ) begin
        \$38  = 16'h0000;
      end
    end
    if (rst) begin
      \$38  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$1 ) begin end
    \$39  = track_bit_cntr_p;
    if (decoder_enable) begin
      \$39  = track_bit_cntr[2:0];
    end
    if (rst) begin
      \$39  = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$1 ) begin end
    \$40  = track_byte_shift;
    if (decoder_enable) begin
      (* full_case = 32'd1 *)
      if (\$24 ) begin
        \$40  = \$25 ;
      end else begin
        \$40  = { track_byte_shift[6:0], 1'h0 };
      end
    end
    if (rst) begin
      \$40  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$1 ) begin end
    \$41  = bit_cntr;
    if (decoder_enable) begin
      \$41  = \$26 [2:0];
      if (block_sync) begin
        \$41  = 3'h0;
      end
    end
    if (rst) begin
      \$41  = 3'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$1 ) begin end
    \$42  = read_bits;
    if (decoder_enable) begin
      \$42  = { read_bits[8:0], track_byte_shift[7] };
    end
    if (rst) begin
      \$42  = 10'h000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$1 ) begin end
    \$43  = \o_pb$75 [1:0];
    if (rst) begin
      \$43  = 2'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$1 ) begin end
    \$44  = o_track_no;
    if (\$30 ) begin
      \$44  = \$35 [6:0];
    end else if (\$34 ) begin
      \$44  = \$36 [6:0];
    end
    if (rst) begin
      \$44  = 7'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$1 ) begin end
    cpu_di = 8'h00;
    if (\$1 ) begin
      cpu_di = i_ram_data;
    end else if (\$4 ) begin
      cpu_di = o_data;
    end else if (\$7 ) begin
      cpu_di = \o_data$30 ;
    end else if (\$10 ) begin
      cpu_di = i_rom_data;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$1 ) begin end
    ram_cs = 1'h0;
    if (\$1 ) begin
      ram_cs = 1'h1;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$1 ) begin end
    via1_cs = 1'h0;
    if (\$1 ) begin
    end else if (\$4 ) begin
      via1_cs = 1'h1;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$1 ) begin end
    via2_cs = 1'h0;
    if (\$1 ) begin
    end else if (\$4 ) begin
    end else if (\$7 ) begin
      via2_cs = 1'h1;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$1 ) begin end
    rom_cs = 1'h0;
    if (\$1 ) begin
    end else if (\$4 ) begin
    end else if (\$7 ) begin
    end else if (\$10 ) begin
      rom_cs = 1'h1;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$1 ) begin end
    \$37  = decoder_enable_cntr;
    if (i_clk_1mhz_ph2_en) begin
      \$37  = \$21 [1:0];
    end
    if (rst) begin
      \$37  = 2'h0;
    end
  end
  assign cpu_addr = o_addr;
  assign o_debug_valid = i_clk_1mhz_ph1_en;
  assign o_debug_sync = o_debug_6502_sync;
  assign o_debug_addr = o_addr;
  assign o_debug_data = o_debug_6502_data;
  assign o_debug_regs = 64'h0000000000000000;
  assign i_data = cpu_di;
  assign \o_addr$42  = o_addr;
  assign o_we = cpu_we;
  assign cpu_do = o_ram_data;
  assign \o_data$46  = o_ram_data;
  assign clk_1mhz_ph1_en = i_clk_1mhz_ph1_en;
  assign clk_1mhz_ph2_en = i_clk_1mhz_ph2_en;
  assign clk_1mhz_ph_en = i_clk_1mhz_ph2_en;
  assign i_cs = via1_cs;
  assign i_addr = o_addr[3:0];
  assign i_we = cpu_we;
  assign \i_data$53  = o_ram_data;
  assign \clk_1mhz_ph_en$54  = i_clk_1mhz_ph2_en;
  assign \i_cs$55  = via2_cs;
  assign \i_addr$56  = o_addr[3:0];
  assign \i_we$57  = cpu_we;
  assign \i_data$58  = o_ram_data;
  assign \byte  = read_bits[7:0];
  assign atna = o_pb[4];
  assign i_pa = read_bits[7:0];
  assign i_so = byte_sync;
  assign head_step_dir = \o_pb$75 [1:0];
  assign motor_ctrl = \o_pb$75 [2];
  assign led_ctrl = \o_pb$75 [3];
  assign write_protect = 1'h0;
  assign data_density = \o_pb$75 [6:5];
  assign track_no = o_track_no;
  assign o_track_addr = track_bit_cntr[15:5];
  assign o_led_on = \o_pb$75 [3];
  assign o_motor_on = \o_pb$75 [2];
  assign o_debug_6502_valid = i_clk_1mhz_ph1_en;
  assign o_debug_6502_addr = o_addr;
  assign o_debug_6502_regs = 64'h0000000000000000;
  assign \i_pb$78 [7] = \$20 ;
  assign \i_pb$78 [4] = 1'h0;
  assign { \i_pb$78 [6:5], \i_pb$78 [3:0] } = 6'h00;
  assign i_pb[7] = \$19 ;
  assign i_pb[2] = \$18 ;
  assign i_pb[0] = \$13 ;
  assign { i_pb[6:3], i_pb[1] } = 5'h00;
endmodule

(* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:44" *)
(* generator = "Amaranth" *)
module \my1541_top.u_cpu_ (clk_1mhz_ph2_en, clk, rst, i_irq, i_so, o_we, o_addr, o_data, o_debug_sync, i_data, data_ir, o_debug_valid);
  reg \$auto$verilog_backend.cc:2445:dump_module$2  = 0;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:28" *)
  input clk_1mhz_ph2_en;
  wire clk_1mhz_ph2_en;
  (* src = "/private/tmp/myc64-amaranth-venv/lib/python3.14/site-packages/amaranth/hdl/_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "/private/tmp/myc64-amaranth-venv/lib/python3.14/site-packages/amaranth/hdl/_ir.py:283" *)
  input rst;
  wire rst;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:33" *)
  input i_irq;
  wire i_irq;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:35" *)
  input i_so;
  wire i_so;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:32" *)
  output o_we;
  wire o_we;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:39" *)
  output [15:0] o_addr;
  wire [15:0] o_addr;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:50" *)
  output [7:0] o_data;
  wire [7:0] o_data;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:52" *)
  output o_debug_sync;
  wire o_debug_sync;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:30" *)
  input [7:0] i_data;
  wire [7:0] i_data;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:40" *)
  output [7:0] data_ir;
  reg [7:0] data_ir = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:27" *)
  input o_debug_valid;
  wire o_debug_valid;
  wire \$1 ;
  wire \$2 ;
  wire \$3 ;
  wire \$4 ;
  reg [7:0] \$5 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:49" *)
  wire [23:0] addr;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:27" *)
  wire clk_1mhz_ph1_en;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:50" *)
  wire [7:0] data_o;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:39" *)
  wire [15:0] o_debug_addr;
  (* init = 8'h00 *)
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:40" *)
  wire [7:0] o_debug_data;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:52" *)
  wire sync;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:51" *)
  wire we_n;
  assign \$4  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:68" *) i_so;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:54" *)
  always @(posedge clk)
    data_ir <= \$5 ;
  assign o_we = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:77" *) we_n;
  assign \$1  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:61" *) rst;
  assign \$2  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:66" *) i_irq;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/cpu6502.py:58" *)
  T65 u_6502 (
    .A(addr),
    .Abort_n(1'h1),
    .BCD_en(1'h1),
    .Clk(clk),
    .DI(data_ir),
    .DO(o_data),
    .Enable(o_debug_valid),
    .IRQ_n(\$2 ),
    .Mode(2'h0),
    .NMI_n(1'h1),
    .R_W_n(we_n),
    .Rdy(1'h1),
    .Res_n(\$1 ),
    .SO_n(\$4 ),
    .Sync(o_debug_sync)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$2 ) begin end
    \$5  = data_ir;
    if (clk_1mhz_ph2_en) begin
      \$5  = i_data;
    end
    if (rst) begin
      \$5  = 8'h00;
    end
  end
  assign data_o = o_data;
  assign clk_1mhz_ph1_en = o_debug_valid;
  assign sync = o_debug_sync;
  assign o_debug_addr = addr[15:0];
  assign o_debug_data = data_ir;
  assign o_addr = addr[15:0];
  assign \$3  = 1'h1;
endmodule

(* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:54" *)
(* generator = "Amaranth" *)
module \my1541_top.u_via1 (clk, rst, i_ca1, i_we, i_addr, i_data, o_irq, i_cs, i_pb, reg_orb, o_data, clk_1mhz_ph_en);
  reg \$auto$verilog_backend.cc:2445:dump_module$3  = 0;
  (* src = "/private/tmp/myc64-amaranth-venv/lib/python3.14/site-packages/amaranth/hdl/_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "/private/tmp/myc64-amaranth-venv/lib/python3.14/site-packages/amaranth/hdl/_ir.py:283" *)
  input rst;
  wire rst;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:42" *)
  input i_ca1;
  wire i_ca1;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:33" *)
  input i_we;
  wire i_we;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:32" *)
  input [3:0] i_addr;
  wire [3:0] i_addr;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:34" *)
  input [7:0] i_data;
  wire [7:0] i_data;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:101" *)
  output o_irq;
  wire o_irq;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:31" *)
  input i_cs;
  wire i_cs;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:39" *)
  input [7:0] i_pb;
  wire [7:0] i_pb;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:40" *)
  output [7:0] reg_orb;
  reg [7:0] reg_orb = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:35" *)
  output [7:0] o_data;
  reg [7:0] o_data;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:30" *)
  input clk_1mhz_ph_en;
  wire clk_1mhz_ph_en;
  wire \$1 ;
  wire [6:0] \$10 ;
  wire [6:0] \$11 ;
  wire [6:0] \$12 ;
  wire [6:0] \$13 ;
  wire \$14 ;
  wire \$15 ;
  wire \$16 ;
  wire \$17 ;
  wire \$18 ;
  wire \$19 ;
  wire \$2 ;
  wire \$20 ;
  wire \$21 ;
  wire \$22 ;
  wire [7:0] \$23 ;
  wire \$24 ;
  wire [7:0] \$25 ;
  wire \$26 ;
  wire [7:0] \$27 ;
  wire \$28 ;
  wire [7:0] \$29 ;
  wire \$3 ;
  wire \$30 ;
  wire [7:0] \$31 ;
  wire \$32 ;
  wire [7:0] \$33 ;
  wire \$34 ;
  wire [7:0] \$35 ;
  wire \$36 ;
  wire [7:0] \$37 ;
  wire \$38 ;
  wire [7:0] \$39 ;
  wire \$4 ;
  wire \$40 ;
  wire [7:0] \$41 ;
  wire \$42 ;
  wire [7:0] \$43 ;
  wire \$44 ;
  wire [7:0] \$45 ;
  wire \$46 ;
  wire [7:0] \$47 ;
  wire \$48 ;
  wire [7:0] \$49 ;
  wire [16:0] \$5 ;
  wire \$50 ;
  wire [7:0] \$51 ;
  wire \$52 ;
  wire [7:0] \$53 ;
  wire \$54 ;
  wire [6:0] \$55 ;
  reg \$56 ;
  reg \$57 ;
  reg [7:0] \$58 ;
  reg [7:0] \$59 ;
  wire \$6 ;
  reg [15:0] \$60 ;
  reg [6:0] \$61 ;
  reg \$62 ;
  reg [7:0] \$63 ;
  reg [7:0] \$64 ;
  reg [7:0] \$65 ;
  reg [7:0] \$66 ;
  reg [7:0] \$67 ;
  reg [7:0] \$68 ;
  reg [6:0] \$69 ;
  wire \$7 ;
  reg [7:0] \$70 ;
  reg [7:0] \$71 ;
  wire \$8 ;
  wire [6:0] \$9 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:96" *)
  wire acr_pa_latching;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:97" *)
  wire acr_pb_latching;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:109" *)
  reg ca1_p = 1'h0;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:110" *)
  reg cb1_p = 1'h0;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:46" *)
  wire i_cb1;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:37" *)
  wire [7:0] i_pa;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:101" *)
  wire irq;
  (* init = 8'h00 *)
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:38" *)
  wire [7:0] o_pa;
  (* init = 8'h00 *)
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:40" *)
  wire [7:0] o_pb;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:106" *)
  reg [7:0] pa_latch = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:107" *)
  reg [7:0] pb_latch = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:89" *)
  reg [7:0] reg_acr = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:87" *)
  reg [7:0] reg_ddra = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:88" *)
  reg [7:0] reg_ddrb = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:92" *)
  reg [6:0] reg_ier = 7'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:91" *)
  reg [6:0] reg_ifr = 7'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:83" *)
  reg [7:0] reg_ora = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:90" *)
  reg [7:0] reg_pcr = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:94" *)
  reg [7:0] reg_t1l_h = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:93" *)
  reg [7:0] reg_t1l_l = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:99" *)
  reg [15:0] timer1_cntr = 16'h0000;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:100" *)
  reg timer1_en = 1'h0;
  assign \$29  = reg_acr[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:174" *) pb_latch : i_pb;
  assign \$30  = reg_ddrb[3] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:173" *) reg_orb[3] : \$29 [3];
  assign \$31  = reg_acr[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:174" *) pb_latch : i_pb;
  assign \$32  = reg_ddrb[4] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:173" *) reg_orb[4] : \$31 [4];
  assign \$33  = reg_acr[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:174" *) pb_latch : i_pb;
  assign \$34  = reg_ddrb[5] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:173" *) reg_orb[5] : \$33 [5];
  assign \$35  = reg_acr[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:174" *) pb_latch : i_pb;
  assign \$36  = reg_ddrb[6] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:173" *) reg_orb[6] : \$35 [6];
  assign \$37  = reg_acr[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:174" *) pb_latch : i_pb;
  assign \$38  = reg_ddrb[7] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:173" *) reg_orb[7] : \$37 [7];
  assign \$39  = reg_acr[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:179" *) pa_latch : 8'h00;
  assign \$40  = reg_ddra[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:178" *) reg_ora[0] : \$39 [0];
  assign \$41  = reg_acr[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:179" *) pa_latch : 8'h00;
  assign \$42  = reg_ddra[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:178" *) reg_ora[1] : \$41 [1];
  assign \$43  = reg_acr[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:179" *) pa_latch : 8'h00;
  assign \$44  = reg_ddra[2] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:178" *) reg_ora[2] : \$43 [2];
  assign \$45  = reg_acr[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:179" *) pa_latch : 8'h00;
  assign \$46  = reg_ddra[3] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:178" *) reg_ora[3] : \$45 [3];
  assign \$47  = reg_acr[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:179" *) pa_latch : 8'h00;
  assign \$48  = reg_ddra[4] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:178" *) reg_ora[4] : \$47 [4];
  assign \$49  = reg_acr[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:179" *) pa_latch : 8'h00;
  assign \$50  = reg_ddra[5] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:178" *) reg_ora[5] : \$49 [5];
  assign \$51  = reg_acr[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:179" *) pa_latch : 8'h00;
  assign \$52  = reg_ddra[6] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:178" *) reg_ora[6] : \$51 [6];
  assign \$53  = reg_acr[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:179" *) pa_latch : 8'h00;
  assign \$54  = reg_ddra[7] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:178" *) reg_ora[7] : \$53 [7];
  assign \$55  = reg_ifr & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:208" *) reg_ier;
  assign o_irq = | (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:208" *) \$55 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:109" *)
  always @(posedge clk)
    ca1_p <= \$56 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:110" *)
  always @(posedge clk)
    cb1_p <= \$57 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:106" *)
  always @(posedge clk)
    pa_latch <= \$58 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:107" *)
  always @(posedge clk)
    pb_latch <= \$59 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:99" *)
  always @(posedge clk)
    timer1_cntr <= \$60 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:91" *)
  always @(posedge clk)
    reg_ifr <= \$61 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:100" *)
  always @(posedge clk)
    timer1_en <= \$62 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:84" *)
  always @(posedge clk)
    reg_orb <= \$63 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:83" *)
  always @(posedge clk)
    reg_ora <= \$64 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:88" *)
  always @(posedge clk)
    reg_ddrb <= \$65 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:87" *)
  always @(posedge clk)
    reg_ddra <= \$66 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:89" *)
  always @(posedge clk)
    reg_acr <= \$67 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:90" *)
  always @(posedge clk)
    reg_pcr <= \$68 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:92" *)
  always @(posedge clk)
    reg_ier <= \$69 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:93" *)
  always @(posedge clk)
    reg_t1l_l <= \$70 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:94" *)
  always @(posedge clk)
    reg_t1l_h <= \$71 ;
  assign \$1  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:114" *) i_ca1;
  assign \$2  = ca1_p & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:114" *) \$1 ;
  assign \$5  = timer1_cntr - (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:120" *) 1'h1;
  assign \$6  = ! (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:121" *) timer1_cntr;
  assign \$7  = clk_1mhz_ph_en & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:134" *) i_cs;
  assign \$8  = \$7  & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:134" *) i_we;
  assign \$9  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:150" *) i_data[6:0];
  assign \$10  = reg_ifr & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:150" *) \$9 ;
  assign \$11  = reg_ier | (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:153" *) i_data[6:0];
  assign \$12  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:155" *) i_data[6:0];
  assign \$13  = reg_ier & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:155" *) \$12 ;
  assign \$14  = clk_1mhz_ph_en & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:168" *) i_cs;
  assign \$15  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:168" *) i_we;
  assign \$16  = \$14  & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:168" *) \$15 ;
  assign \$17  = ca1_p != (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:205" *) i_ca1;
  assign \$18  = i_ca1 == (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:205" *) reg_pcr[0];
  assign \$19  = \$17  & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:205" *) \$18 ;
  assign \$20  = clk_1mhz_ph_en & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:168" *) i_cs;
  assign \$21  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:168" *) i_we;
  assign \$22  = \$20  & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:168" *) \$21 ;
  assign \$23  = reg_acr[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:174" *) pb_latch : i_pb;
  assign \$24  = reg_ddrb[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:173" *) reg_orb[0] : \$23 [0];
  assign \$25  = reg_acr[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:174" *) pb_latch : i_pb;
  assign \$26  = reg_ddrb[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:173" *) reg_orb[1] : \$25 [1];
  assign \$27  = reg_acr[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:174" *) pb_latch : i_pb;
  assign \$28  = reg_ddrb[2] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:173" *) reg_orb[2] : \$27 [2];
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$3 ) begin end
    \$56  = ca1_p;
    if (clk_1mhz_ph_en) begin
      \$56  = i_ca1;
    end
    if (rst) begin
      \$56  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$3 ) begin end
    \$57  = cb1_p;
    if (clk_1mhz_ph_en) begin
      \$57  = 1'h0;
    end
    if (rst) begin
      \$57  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$3 ) begin end
    \$58  = pa_latch;
    if (clk_1mhz_ph_en) begin
      if (\$2 ) begin
        \$58  = 8'h00;
      end
    end
    if (rst) begin
      \$58  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$3 ) begin end
    \$59  = pb_latch;
    if (clk_1mhz_ph_en) begin
      if (\$4 ) begin
        \$59  = i_pb;
      end
    end
    if (rst) begin
      \$59  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$3 ) begin end
    \$60  = timer1_cntr;
    if (clk_1mhz_ph_en) begin
      if (timer1_en) begin
        \$60  = \$5 [15:0];
        if (\$6 ) begin
          casez (reg_acr[7:6])
            2'h0:
                /* empty */;
            2'h1:
                \$60  = { reg_t1l_h, reg_t1l_l };
          endcase
        end
      end
    end
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            /* empty */;
        4'h2:
            /* empty */;
        4'h3:
            /* empty */;
        4'hb:
            /* empty */;
        4'hc:
            /* empty */;
        4'hd:
            /* empty */;
        4'he:
            /* empty */;
        4'h4:
            /* empty */;
        4'h5:
            \$60  = { i_data, reg_t1l_l };
      endcase
    end
    if (rst) begin
      \$60  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$3 ) begin end
    \$61  = reg_ifr;
    if (clk_1mhz_ph_en) begin
      if (timer1_en) begin
        if (\$6 ) begin
          \$61 [6] = 1'h1;
        end
      end
    end
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            \$61 [1] = 1'h0;
        4'h2:
            /* empty */;
        4'h3:
            /* empty */;
        4'hb:
            /* empty */;
        4'hc:
            /* empty */;
        4'hd:
            \$61  = \$10 ;
        4'he:
            /* empty */;
        4'h4:
            /* empty */;
        4'h5:
            \$61 [6] = 1'h0;
        4'h6:
            /* empty */;
        4'h7:
            \$61 [6] = 1'h0;
      endcase
    end
    if (\$16 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            \$61 [1] = 1'h0;
        4'h2:
            /* empty */;
        4'h3:
            /* empty */;
        4'hb:
            /* empty */;
        4'hc:
            /* empty */;
        4'hd:
            /* empty */;
        4'he:
            /* empty */;
        4'h4:
            \$61 [6] = 1'h0;
        4'h5:
            /* empty */;
        4'h6:
            \$61 [6] = 1'h0;
      endcase
    end
    if (\$19 ) begin
      \$61 [1] = 1'h1;
    end
    if (rst) begin
      \$61  = 7'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$3 ) begin end
    \$62  = timer1_en;
    if (clk_1mhz_ph_en) begin
      if (timer1_en) begin
        if (\$6 ) begin
          casez (reg_acr[7:6])
            2'h0:
                \$62  = 1'h0;
          endcase
        end
      end
    end
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            /* empty */;
        4'h2:
            /* empty */;
        4'h3:
            /* empty */;
        4'hb:
            /* empty */;
        4'hc:
            /* empty */;
        4'hd:
            /* empty */;
        4'he:
            /* empty */;
        4'h4:
            /* empty */;
        4'h5:
            \$62  = 1'h1;
      endcase
    end
    if (rst) begin
      \$62  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$3 ) begin end
    \$63  = reg_orb;
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            \$63  = i_data;
      endcase
    end
    if (rst) begin
      \$63  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$3 ) begin end
    \$64  = reg_ora;
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            \$64  = i_data;
      endcase
    end
    if (rst) begin
      \$64  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$3 ) begin end
    \$65  = reg_ddrb;
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            /* empty */;
        4'h2:
            \$65  = i_data;
      endcase
    end
    if (rst) begin
      \$65  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$3 ) begin end
    \$66  = reg_ddra;
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            /* empty */;
        4'h2:
            /* empty */;
        4'h3:
            \$66  = i_data;
      endcase
    end
    if (rst) begin
      \$66  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$3 ) begin end
    \$67  = reg_acr;
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            /* empty */;
        4'h2:
            /* empty */;
        4'h3:
            /* empty */;
        4'hb:
            \$67  = i_data;
      endcase
    end
    if (rst) begin
      \$67  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$3 ) begin end
    \$68  = reg_pcr;
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            /* empty */;
        4'h2:
            /* empty */;
        4'h3:
            /* empty */;
        4'hb:
            /* empty */;
        4'hc:
            \$68  = i_data;
      endcase
    end
    if (rst) begin
      \$68  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$3 ) begin end
    \$69  = reg_ier;
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            /* empty */;
        4'h2:
            /* empty */;
        4'h3:
            /* empty */;
        4'hb:
            /* empty */;
        4'hc:
            /* empty */;
        4'hd:
            /* empty */;
        4'he:
            (* full_case = 32'd1 *)
            if (i_data[7]) begin
              \$69  = \$11 ;
            end else begin
              \$69  = \$13 ;
            end
      endcase
    end
    if (rst) begin
      \$69  = 7'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$3 ) begin end
    \$70  = reg_t1l_l;
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            /* empty */;
        4'h2:
            /* empty */;
        4'h3:
            /* empty */;
        4'hb:
            /* empty */;
        4'hc:
            /* empty */;
        4'hd:
            /* empty */;
        4'he:
            /* empty */;
        4'h4:
            \$70  = i_data;
        4'h5:
            /* empty */;
        4'h6:
            \$70  = i_data;
      endcase
    end
    if (rst) begin
      \$70  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$3 ) begin end
    \$71  = reg_t1l_h;
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            /* empty */;
        4'h2:
            /* empty */;
        4'h3:
            /* empty */;
        4'hb:
            /* empty */;
        4'hc:
            /* empty */;
        4'hd:
            /* empty */;
        4'he:
            /* empty */;
        4'h4:
            /* empty */;
        4'h5:
            /* empty */;
        4'h6:
            /* empty */;
        4'h7:
            \$71  = i_data;
      endcase
    end
    if (rst) begin
      \$71  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$3 ) begin end
    o_data = 8'h00;
    if (\$22 ) begin
      casez (i_addr)
        4'h0:
          begin
            o_data[0] = \$24 ;
            o_data[1] = \$26 ;
            o_data[2] = \$28 ;
            o_data[3] = \$30 ;
            o_data[4] = \$32 ;
            o_data[5] = \$34 ;
            o_data[6] = \$36 ;
            o_data[7] = \$38 ;
          end
        4'h1:
          begin
            o_data[0] = \$40 ;
            o_data[1] = \$42 ;
            o_data[2] = \$44 ;
            o_data[3] = \$46 ;
            o_data[4] = \$48 ;
            o_data[5] = \$50 ;
            o_data[6] = \$52 ;
            o_data[7] = \$54 ;
          end
        4'h2:
            o_data = reg_ddrb;
        4'h3:
            o_data = reg_ddra;
        4'hb:
            o_data = reg_acr;
        4'hc:
            o_data = reg_pcr;
        4'hd:
            o_data = { o_irq, reg_ifr };
        4'he:
            o_data = { 1'h1, reg_ier };
        4'h4:
            o_data = timer1_cntr[7:0];
        4'h5:
            o_data = timer1_cntr[15:8];
        4'h6:
            o_data = reg_t1l_l;
        4'h7:
            o_data = reg_t1l_h;
      endcase
    end
  end
  assign i_cb1 = 1'h0;
  assign i_pa = 8'h00;
  assign acr_pa_latching = reg_acr[0];
  assign acr_pb_latching = reg_acr[1];
  assign o_pa = reg_ora;
  assign o_pb = reg_orb;
  assign irq = o_irq;
  assign \$3  = 1'h1;
  assign \$4  = cb1_p;
endmodule

(* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:54" *)
(* generator = "Amaranth" *)
module \my1541_top.u_via2 (clk, rst, i_ca1, i_we, i_addr, i_data, o_irq, i_cs, i_pb, i_pa, reg_orb, o_data, clk_1mhz_ph_en);
  reg \$auto$verilog_backend.cc:2445:dump_module$4  = 0;
  (* src = "/private/tmp/myc64-amaranth-venv/lib/python3.14/site-packages/amaranth/hdl/_ir.py:283" *)
  input clk;
  wire clk;
  (* src = "/private/tmp/myc64-amaranth-venv/lib/python3.14/site-packages/amaranth/hdl/_ir.py:283" *)
  input rst;
  wire rst;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:42" *)
  input i_ca1;
  wire i_ca1;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:33" *)
  input i_we;
  wire i_we;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:32" *)
  input [3:0] i_addr;
  wire [3:0] i_addr;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:34" *)
  input [7:0] i_data;
  wire [7:0] i_data;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:101" *)
  output o_irq;
  wire o_irq;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:31" *)
  input i_cs;
  wire i_cs;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:39" *)
  input [7:0] i_pb;
  wire [7:0] i_pb;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:37" *)
  input [7:0] i_pa;
  wire [7:0] i_pa;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:40" *)
  output [7:0] reg_orb;
  reg [7:0] reg_orb = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:35" *)
  output [7:0] o_data;
  reg [7:0] o_data;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:30" *)
  input clk_1mhz_ph_en;
  wire clk_1mhz_ph_en;
  wire \$1 ;
  wire [6:0] \$10 ;
  wire [6:0] \$11 ;
  wire [6:0] \$12 ;
  wire [6:0] \$13 ;
  wire \$14 ;
  wire \$15 ;
  wire \$16 ;
  wire \$17 ;
  wire \$18 ;
  wire \$19 ;
  wire \$2 ;
  wire \$20 ;
  wire \$21 ;
  wire \$22 ;
  wire [7:0] \$23 ;
  wire \$24 ;
  wire [7:0] \$25 ;
  wire \$26 ;
  wire [7:0] \$27 ;
  wire \$28 ;
  wire [7:0] \$29 ;
  wire \$3 ;
  wire \$30 ;
  wire [7:0] \$31 ;
  wire \$32 ;
  wire [7:0] \$33 ;
  wire \$34 ;
  wire [7:0] \$35 ;
  wire \$36 ;
  wire [7:0] \$37 ;
  wire \$38 ;
  wire [7:0] \$39 ;
  wire \$4 ;
  wire \$40 ;
  wire [7:0] \$41 ;
  wire \$42 ;
  wire [7:0] \$43 ;
  wire \$44 ;
  wire [7:0] \$45 ;
  wire \$46 ;
  wire [7:0] \$47 ;
  wire \$48 ;
  wire [7:0] \$49 ;
  wire [16:0] \$5 ;
  wire \$50 ;
  wire [7:0] \$51 ;
  wire \$52 ;
  wire [7:0] \$53 ;
  wire \$54 ;
  wire [6:0] \$55 ;
  reg \$56 ;
  reg \$57 ;
  reg [7:0] \$58 ;
  reg [7:0] \$59 ;
  wire \$6 ;
  reg [15:0] \$60 ;
  reg [6:0] \$61 ;
  reg \$62 ;
  reg [7:0] \$63 ;
  reg [7:0] \$64 ;
  reg [7:0] \$65 ;
  reg [7:0] \$66 ;
  reg [7:0] \$67 ;
  reg [7:0] \$68 ;
  reg [6:0] \$69 ;
  wire \$7 ;
  reg [7:0] \$70 ;
  reg [7:0] \$71 ;
  wire \$8 ;
  wire [6:0] \$9 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:96" *)
  wire acr_pa_latching;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:97" *)
  wire acr_pb_latching;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:109" *)
  reg ca1_p = 1'h0;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:110" *)
  reg cb1_p = 1'h0;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:46" *)
  wire i_cb1;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:101" *)
  wire irq;
  (* init = 8'h00 *)
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:38" *)
  wire [7:0] o_pa;
  (* init = 8'h00 *)
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:40" *)
  wire [7:0] o_pb;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:106" *)
  reg [7:0] pa_latch = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:107" *)
  reg [7:0] pb_latch = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:89" *)
  reg [7:0] reg_acr = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:87" *)
  reg [7:0] reg_ddra = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:88" *)
  reg [7:0] reg_ddrb = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:92" *)
  reg [6:0] reg_ier = 7'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:91" *)
  reg [6:0] reg_ifr = 7'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:83" *)
  reg [7:0] reg_ora = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:90" *)
  reg [7:0] reg_pcr = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:94" *)
  reg [7:0] reg_t1l_h = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:93" *)
  reg [7:0] reg_t1l_l = 8'h00;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:99" *)
  reg [15:0] timer1_cntr = 16'h0000;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:100" *)
  reg timer1_en = 1'h0;
  assign \$29  = reg_acr[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:174" *) pb_latch : i_pb;
  assign \$30  = reg_ddrb[3] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:173" *) reg_orb[3] : \$29 [3];
  assign \$31  = reg_acr[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:174" *) pb_latch : i_pb;
  assign \$32  = reg_ddrb[4] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:173" *) reg_orb[4] : \$31 [4];
  assign \$33  = reg_acr[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:174" *) pb_latch : i_pb;
  assign \$34  = reg_ddrb[5] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:173" *) reg_orb[5] : \$33 [5];
  assign \$35  = reg_acr[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:174" *) pb_latch : i_pb;
  assign \$36  = reg_ddrb[6] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:173" *) reg_orb[6] : \$35 [6];
  assign \$37  = reg_acr[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:174" *) pb_latch : i_pb;
  assign \$38  = reg_ddrb[7] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:173" *) reg_orb[7] : \$37 [7];
  assign \$39  = reg_acr[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:179" *) pa_latch : i_pa;
  assign \$40  = reg_ddra[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:178" *) reg_ora[0] : \$39 [0];
  assign \$41  = reg_acr[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:179" *) pa_latch : i_pa;
  assign \$42  = reg_ddra[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:178" *) reg_ora[1] : \$41 [1];
  assign \$43  = reg_acr[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:179" *) pa_latch : i_pa;
  assign \$44  = reg_ddra[2] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:178" *) reg_ora[2] : \$43 [2];
  assign \$45  = reg_acr[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:179" *) pa_latch : i_pa;
  assign \$46  = reg_ddra[3] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:178" *) reg_ora[3] : \$45 [3];
  assign \$47  = reg_acr[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:179" *) pa_latch : i_pa;
  assign \$48  = reg_ddra[4] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:178" *) reg_ora[4] : \$47 [4];
  assign \$49  = reg_acr[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:179" *) pa_latch : i_pa;
  assign \$50  = reg_ddra[5] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:178" *) reg_ora[5] : \$49 [5];
  assign \$51  = reg_acr[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:179" *) pa_latch : i_pa;
  assign \$52  = reg_ddra[6] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:178" *) reg_ora[6] : \$51 [6];
  assign \$53  = reg_acr[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:179" *) pa_latch : i_pa;
  assign \$54  = reg_ddra[7] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:178" *) reg_ora[7] : \$53 [7];
  assign \$55  = reg_ifr & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:208" *) reg_ier;
  assign o_irq = | (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:208" *) \$55 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:109" *)
  always @(posedge clk)
    ca1_p <= \$56 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:110" *)
  always @(posedge clk)
    cb1_p <= \$57 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:106" *)
  always @(posedge clk)
    pa_latch <= \$58 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:107" *)
  always @(posedge clk)
    pb_latch <= \$59 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:99" *)
  always @(posedge clk)
    timer1_cntr <= \$60 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:91" *)
  always @(posedge clk)
    reg_ifr <= \$61 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:100" *)
  always @(posedge clk)
    timer1_en <= \$62 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:84" *)
  always @(posedge clk)
    reg_orb <= \$63 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:83" *)
  always @(posedge clk)
    reg_ora <= \$64 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:88" *)
  always @(posedge clk)
    reg_ddrb <= \$65 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:87" *)
  always @(posedge clk)
    reg_ddra <= \$66 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:89" *)
  always @(posedge clk)
    reg_acr <= \$67 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:90" *)
  always @(posedge clk)
    reg_pcr <= \$68 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:92" *)
  always @(posedge clk)
    reg_ier <= \$69 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:93" *)
  always @(posedge clk)
    reg_t1l_l <= \$70 ;
  (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:94" *)
  always @(posedge clk)
    reg_t1l_h <= \$71 ;
  assign \$1  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:114" *) i_ca1;
  assign \$2  = ca1_p & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:114" *) \$1 ;
  assign \$5  = timer1_cntr - (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:120" *) 1'h1;
  assign \$6  = ! (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:121" *) timer1_cntr;
  assign \$7  = clk_1mhz_ph_en & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:134" *) i_cs;
  assign \$8  = \$7  & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:134" *) i_we;
  assign \$9  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:150" *) i_data[6:0];
  assign \$10  = reg_ifr & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:150" *) \$9 ;
  assign \$11  = reg_ier | (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:153" *) i_data[6:0];
  assign \$12  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:155" *) i_data[6:0];
  assign \$13  = reg_ier & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:155" *) \$12 ;
  assign \$14  = clk_1mhz_ph_en & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:168" *) i_cs;
  assign \$15  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:168" *) i_we;
  assign \$16  = \$14  & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:168" *) \$15 ;
  assign \$17  = ca1_p != (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:205" *) i_ca1;
  assign \$18  = i_ca1 == (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:205" *) reg_pcr[0];
  assign \$19  = \$17  & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:205" *) \$18 ;
  assign \$20  = clk_1mhz_ph_en & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:168" *) i_cs;
  assign \$21  = ~ (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:168" *) i_we;
  assign \$22  = \$20  & (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:168" *) \$21 ;
  assign \$23  = reg_acr[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:174" *) pb_latch : i_pb;
  assign \$24  = reg_ddrb[0] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:173" *) reg_orb[0] : \$23 [0];
  assign \$25  = reg_acr[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:174" *) pb_latch : i_pb;
  assign \$26  = reg_ddrb[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:173" *) reg_orb[1] : \$25 [1];
  assign \$27  = reg_acr[1] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:174" *) pb_latch : i_pb;
  assign \$28  = reg_ddrb[2] ? (* src = "/Users/ericlewis/Developer/myc64-pocket/src/fpga/core/my1541-rtl/via.py:173" *) reg_orb[2] : \$27 [2];
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$4 ) begin end
    \$56  = ca1_p;
    if (clk_1mhz_ph_en) begin
      \$56  = i_ca1;
    end
    if (rst) begin
      \$56  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$4 ) begin end
    \$57  = cb1_p;
    if (clk_1mhz_ph_en) begin
      \$57  = 1'h0;
    end
    if (rst) begin
      \$57  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$4 ) begin end
    \$58  = pa_latch;
    if (clk_1mhz_ph_en) begin
      if (\$2 ) begin
        \$58  = i_pa;
      end
    end
    if (rst) begin
      \$58  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$4 ) begin end
    \$59  = pb_latch;
    if (clk_1mhz_ph_en) begin
      if (\$4 ) begin
        \$59  = i_pb;
      end
    end
    if (rst) begin
      \$59  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$4 ) begin end
    \$60  = timer1_cntr;
    if (clk_1mhz_ph_en) begin
      if (timer1_en) begin
        \$60  = \$5 [15:0];
        if (\$6 ) begin
          casez (reg_acr[7:6])
            2'h0:
                /* empty */;
            2'h1:
                \$60  = { reg_t1l_h, reg_t1l_l };
          endcase
        end
      end
    end
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            /* empty */;
        4'h2:
            /* empty */;
        4'h3:
            /* empty */;
        4'hb:
            /* empty */;
        4'hc:
            /* empty */;
        4'hd:
            /* empty */;
        4'he:
            /* empty */;
        4'h4:
            /* empty */;
        4'h5:
            \$60  = { i_data, reg_t1l_l };
      endcase
    end
    if (rst) begin
      \$60  = 16'h0000;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$4 ) begin end
    \$61  = reg_ifr;
    if (clk_1mhz_ph_en) begin
      if (timer1_en) begin
        if (\$6 ) begin
          \$61 [6] = 1'h1;
        end
      end
    end
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            \$61 [1] = 1'h0;
        4'h2:
            /* empty */;
        4'h3:
            /* empty */;
        4'hb:
            /* empty */;
        4'hc:
            /* empty */;
        4'hd:
            \$61  = \$10 ;
        4'he:
            /* empty */;
        4'h4:
            /* empty */;
        4'h5:
            \$61 [6] = 1'h0;
        4'h6:
            /* empty */;
        4'h7:
            \$61 [6] = 1'h0;
      endcase
    end
    if (\$16 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            \$61 [1] = 1'h0;
        4'h2:
            /* empty */;
        4'h3:
            /* empty */;
        4'hb:
            /* empty */;
        4'hc:
            /* empty */;
        4'hd:
            /* empty */;
        4'he:
            /* empty */;
        4'h4:
            \$61 [6] = 1'h0;
        4'h5:
            /* empty */;
        4'h6:
            \$61 [6] = 1'h0;
      endcase
    end
    if (\$19 ) begin
      \$61 [1] = 1'h1;
    end
    if (rst) begin
      \$61  = 7'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$4 ) begin end
    \$62  = timer1_en;
    if (clk_1mhz_ph_en) begin
      if (timer1_en) begin
        if (\$6 ) begin
          casez (reg_acr[7:6])
            2'h0:
                \$62  = 1'h0;
          endcase
        end
      end
    end
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            /* empty */;
        4'h2:
            /* empty */;
        4'h3:
            /* empty */;
        4'hb:
            /* empty */;
        4'hc:
            /* empty */;
        4'hd:
            /* empty */;
        4'he:
            /* empty */;
        4'h4:
            /* empty */;
        4'h5:
            \$62  = 1'h1;
      endcase
    end
    if (rst) begin
      \$62  = 1'h0;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$4 ) begin end
    \$63  = reg_orb;
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            \$63  = i_data;
      endcase
    end
    if (rst) begin
      \$63  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$4 ) begin end
    \$64  = reg_ora;
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            \$64  = i_data;
      endcase
    end
    if (rst) begin
      \$64  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$4 ) begin end
    \$65  = reg_ddrb;
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            /* empty */;
        4'h2:
            \$65  = i_data;
      endcase
    end
    if (rst) begin
      \$65  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$4 ) begin end
    \$66  = reg_ddra;
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            /* empty */;
        4'h2:
            /* empty */;
        4'h3:
            \$66  = i_data;
      endcase
    end
    if (rst) begin
      \$66  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$4 ) begin end
    \$67  = reg_acr;
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            /* empty */;
        4'h2:
            /* empty */;
        4'h3:
            /* empty */;
        4'hb:
            \$67  = i_data;
      endcase
    end
    if (rst) begin
      \$67  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$4 ) begin end
    \$68  = reg_pcr;
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            /* empty */;
        4'h2:
            /* empty */;
        4'h3:
            /* empty */;
        4'hb:
            /* empty */;
        4'hc:
            \$68  = i_data;
      endcase
    end
    if (rst) begin
      \$68  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$4 ) begin end
    \$69  = reg_ier;
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            /* empty */;
        4'h2:
            /* empty */;
        4'h3:
            /* empty */;
        4'hb:
            /* empty */;
        4'hc:
            /* empty */;
        4'hd:
            /* empty */;
        4'he:
            (* full_case = 32'd1 *)
            if (i_data[7]) begin
              \$69  = \$11 ;
            end else begin
              \$69  = \$13 ;
            end
      endcase
    end
    if (rst) begin
      \$69  = 7'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$4 ) begin end
    \$70  = reg_t1l_l;
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            /* empty */;
        4'h2:
            /* empty */;
        4'h3:
            /* empty */;
        4'hb:
            /* empty */;
        4'hc:
            /* empty */;
        4'hd:
            /* empty */;
        4'he:
            /* empty */;
        4'h4:
            \$70  = i_data;
        4'h5:
            /* empty */;
        4'h6:
            \$70  = i_data;
      endcase
    end
    if (rst) begin
      \$70  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$4 ) begin end
    \$71  = reg_t1l_h;
    if (\$8 ) begin
      casez (i_addr)
        4'h0:
            /* empty */;
        4'h1:
            /* empty */;
        4'h2:
            /* empty */;
        4'h3:
            /* empty */;
        4'hb:
            /* empty */;
        4'hc:
            /* empty */;
        4'hd:
            /* empty */;
        4'he:
            /* empty */;
        4'h4:
            /* empty */;
        4'h5:
            /* empty */;
        4'h6:
            /* empty */;
        4'h7:
            \$71  = i_data;
      endcase
    end
    if (rst) begin
      \$71  = 8'h00;
    end
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2445:dump_module$4 ) begin end
    o_data = 8'h00;
    if (\$22 ) begin
      casez (i_addr)
        4'h0:
          begin
            o_data[0] = \$24 ;
            o_data[1] = \$26 ;
            o_data[2] = \$28 ;
            o_data[3] = \$30 ;
            o_data[4] = \$32 ;
            o_data[5] = \$34 ;
            o_data[6] = \$36 ;
            o_data[7] = \$38 ;
          end
        4'h1:
          begin
            o_data[0] = \$40 ;
            o_data[1] = \$42 ;
            o_data[2] = \$44 ;
            o_data[3] = \$46 ;
            o_data[4] = \$48 ;
            o_data[5] = \$50 ;
            o_data[6] = \$52 ;
            o_data[7] = \$54 ;
          end
        4'h2:
            o_data = reg_ddrb;
        4'h3:
            o_data = reg_ddra;
        4'hb:
            o_data = reg_acr;
        4'hc:
            o_data = reg_pcr;
        4'hd:
            o_data = { o_irq, reg_ifr };
        4'he:
            o_data = { 1'h1, reg_ier };
        4'h4:
            o_data = timer1_cntr[7:0];
        4'h5:
            o_data = timer1_cntr[15:8];
        4'h6:
            o_data = reg_t1l_l;
        4'h7:
            o_data = reg_t1l_h;
      endcase
    end
  end
  assign i_cb1 = 1'h0;
  assign acr_pa_latching = reg_acr[0];
  assign acr_pb_latching = reg_acr[1];
  assign o_pa = reg_ora;
  assign o_pb = reg_orb;
  assign irq = o_irq;
  assign \$3  = 1'h1;
  assign \$4  = cb1_p;
endmodule
